{
 "title": "Custom dashboard",
 "description": "Custom dashboard for application , Database , CPU , memory and Disk",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(mysql_up,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mysql_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "RAM utilization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ( avg(node_memory_MemAvailable_bytes) / avg(node_memory_MemTotal_bytes) * 100 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application logs 404",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"student-api\", app=\"api\"} |= \" 404\""
    }
   ]
  },
  {
   "title": "Database UPTime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{job=~\"$job\", instance=~\"$instance\"} / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs 200 OK",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"student-api\", app=\"api\"} |= \" 200\""
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( (node_filesystem_size_bytes{instance=\"192.168.49.2:9100\", mountpoint=\"/data\"} - node_filesystem_avail_bytes{instance=\"192.168.49.2:9100\", mountpoint=\"/data\"}) / node_filesystem_size_bytes{instance=\"192.168.49.2:9100\", mountpoint=\"/data\"} ) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}