# Prometheus Configuration (Persistent Storage)
prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 15s
    retention: 2d
    nodeSelector:
      type: dependent-services
    storageSpec: {}
    # volumeClaimTemplate:
    #   spec:
    #     accessModes: ["ReadWriteOnce"]
    #     resources:
    #       requests:
    #         storage: 10Gi  # Set your desired storage size
    # serviceAccount:
    #   create: true
    #   name: prometheus-k8s
    # rbac:
    #   create: true  # Enabling RBAC for Prometheus access to cluster resources
    #   pspEnabled: false
  additionalScrapeConfigs:
    - job_name: 'mysql-exporter'                     # New job for MySQL Exporter
      scrapeInterval: 15s                             # Changed to scrapeInterval
      metrics_path: /metrics
      static_configs:
        - targets: ['mysql-exporter-prometheus-mysql-exporter.student-api.svc:9104']
# Grafana Configuration (Persistent Storage)
grafana:
  enabled: true
  adminPassword: "admin_password"
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  nodeSelector:
    type: dependent-services
  persistence:
    enabled: true
    size: 5Gi  # Set your desired storage size for Grafana
    accessModes:
      - ReadWriteOnce
    storageClassName: ""  # Optionally set to a specific StorageClass, if required
# Enable kube-state-metrics with Role Bindings
kube-state-metrics:
  enabled: true
  nodeSelector:
    type: dependent-services
  rbac:
    create: true
  serviceAccount:
    create: true
    name: kube-state-metrics
# Node Exporter Configuration
nodeExporter:
  enabled: true
  nodeSelector:
    type: dependent-services
  serviceAccount:
    create: true
    name: node-exporter
# Alertmanager Configuration (No Persistence)
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    nodeSelector:
      type: dependent-services