apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-api-secret
  namespace: student-api # The namespace where your app runs
spec:
  refreshInterval: "60s" # How often to refresh the secrets
  secretStoreRef:
    name: vault-secret-store # Reference to the SecretStore defined above
    kind: SecretStore
  target:
    name: mysql-secret # The name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: "mysql" # The name of the secret in Vault
        property: "MYSQL_ROOT_PASSWORD" # Property key in Vault
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: "mysql"
        property: "MYSQL_DATABASE"
    - secretKey: MYSQL_USER
      remoteRef:
        key: "mysql"
        property: "MYSQL_USER"
    - secretKey: MYSQL_HOST
      remoteRef:
        key: "mysql"
        property: "MYSQL_HOST"
    - secretKey: DATABASE_URL
      remoteRef:
        key: "mysql"
        property: "DATABASE_URL"
  dataFrom:
    - extract:
        key: "mysql" # Fetch all secrets from the "mysql" key in Vault
