apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-api-secrets
  namespace: student-api # The namespace where your app runs
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-secret-store # The SecretStore we defined earlier
    kind: SecretStore
  target:
    name: mysql # The name of the Kubernetes Secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: "mysql-secret"
        property: "MYSQL_ROOT_PASSWORD"
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: "mysql-secret"
        property: "MYSQL_DATABASE"
    - secretKey: MYSQL_USER
      remoteRef:
        key: "mysql-secret"
        property: "MYSQL_USER"
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: "mysql-secret"
        property: "MYSQL_PASSWORD"
    - secretKey: MYSQL_HOST
      remoteRef:
        key: "mysql-secret"
        property: "MYSQL_HOST"
