apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: student-api
spec:
  provider:
    vault:
      #server: "http://10.109.76.92:8200" # Use the ClusterIP service for inter-pod communication
      server: http://vault-service.vault.svc.cluster.local:8200
      path: "secret/" # Adjusted to the version 1 API path
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token # Name of the Kubernetes Secret containing the Vault token
          key: token # Key inside the Secret that holds the Vault token
