apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: student-api
spec:
  provider:
    vault:
      server: "{{ .Values.vault.server }}"
      path: "{{ .Values.vault.path }}"
      version: "{{ .Values.vault.version }}"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.tokenSecretName }}
          key: {{ .Values.vault.tokenSecretKey }}
