apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretstore.name }}
  namespace: {{ .Values.secretstore.namespace }}
spec:
  provider:
    vault:
      server: "{{ .Values.vault.server }}"
      path: "{{ .Values.vault.path }}"
      version: "{{ .Values.vault.version }}"
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.auth.tokenSecretRef.name }}
          key: {{ .Values.vault.auth.tokenSecretRef.key }}
