"""Create student table with name, age, and phone_number

Revision ID: 687592955894
Revises: 
Create Date: 2024-09-19 17:24:02.006488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687592955894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
