apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: student-api
data:
  MYSQL_DATABASE: "studentdb1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-api
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlwYXNzd29yZA== # Base64 encoded "mypassword"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: student-api
spec:
  capacity:
    storage: 5Gi # Specify the size of the PV
  accessModes:
    - ReadWriteOnce
  hostPath: # Use hostPath for local development; change for production
    path: /mnt/data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: student-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Must match the size of the PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: student-api
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql # MySQL data directory
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc # Link to the PVC
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: student-api
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
