version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      RUN_MIGRATION: "true"
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - db-database:/var/lib/mysql
    networks:
      - my-network

volumes:
  db-database:


networks:
  my-network:
