version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: $(DATABASE_URL)
      RUN_MIGRATION: false
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
      MYSQL_DATABASE: $(MYSQL_DATABASE)
    ports:
      - '3306:3306'
    volumes:
      - db-database:/var/lib/mysql

volumes:
  db-database: