version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./api.env
    environment:
      RUN_MIGRATION: "true"
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./db.env
    ports:
      - '3306:3306'
    volumes:
      - db-database:/var/lib/mysql

volumes:
  db-database: