version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      RUN_MIGRATION: "true"
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:5000/healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: studentdb1
    ports:
      - '3306:3306'
    volumes:
      - db-database:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db-database:


networks:
  my-network:
