version: '3.8'

services:
  flask-api:
    #image: "${DOCKER_USER}/${DOCKER_IMAGE}:3.0"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #env_file:
    #  - ./api.env
    environment:
      DATABASE_URL: "mysql+pymysql://root:mypassword@db:3306/studentdb1"
      RUN_MIGRATION: "true"
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./db.env
    ports:
      - '3306:3306'
    volumes:
      - db-database:/var/lib/mysql

volumes:
  db-database: