"""Removed phone_number, address & gender

Revision ID: f9d1713847b5
Revises: 
Create Date: 2024-09-26 12:46:11.842756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9d1713847b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
