---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/vault # Update this path as per your host machine's directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc-new # New name for the PVC
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Match the size with the PersistentVolume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault-config.hcl: |
    # Enable the listener
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_addr = "127.0.0.1:8201" #Loopback for cluster communication
      tls_disable = true
    }
    ui = true
    # Specify storage backend
    storage "raft" {
      path = "/vault/data"
      cluster_addr = "http://vault:8201"  # Ensure this is correctly set
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.12.0
          ports:
            - containerPort: 8200
          args:
            - "server"
            - "-config=/vault/config/vault-config.hcl"
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
            - name: config-volume
              mountPath: /vault/config
          securityContext:
            runAsUser: 0 # Run as root user to allow permission changes
            capabilities:
              add:
                - IPC_LOCK # Allow IPC_LOCK capability
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data-pvc-new # Use the new PVC name
        - name: config-volume
          configMap:
            name: vault-config
