apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault-config.hcl: |
    # Enable the listener
    listener "tcp" {
      # Set the address to bind to; this allows Vault to accept incoming requests
      address = "0.0.0.0:8200"
      cluster_addr = "127.0.0.1:8201" #Loopback for cluster communication
      # Disabling TLS for simplicity; enable in production
      tls_disable = true
    }
    ui = true
    # Specify storage backend
    storage "raft" {
      path = "/vault/data"
      # Specify the cluster address for Raft
      cluster_addr = "http://vault:8201"  # Use the service name as the cluster address
    }

    # Define telemetry settings
    # telemetry {
    #   disable = false  # Keep telemetry enabled
    # }
