"""empty message

Revision ID: 18daaed80f96
Revises: 
Create Date: 2024-09-27 11:19:25.748110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18daaed80f96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
