"""Removed the address column.

Revision ID: eea774b7e3e4
Revises: 4439cca41bf4
Create Date: 2024-09-27 15:53:30.477179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eea774b7e3e4'
down_revision = '4439cca41bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
