version: '3'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: studentdb1
      DATABASE_URL: mysql+pymysql://root:mypassword@db:3306/studentdb1
      RUN_MIGRATION: true
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: studentdb1
    ports:
      - '3306:3306'
    volumes:
      - db-database:/var/lib/mysql

volumes:
  db-database: