namespace: student-api
# Secretstore values.yaml
vault:
  server: "http://vault.vault.svc.cluster.local:8200"
  path: "secret/"  # API path for the secret
  version: "v1"
  tokenSecretName: vault-token  # Kubernetes secret name
  tokenSecretKey: token  # Key inside the Kubernetes secret

# Externalsecrets values.yaml
externalSecret:
  name: db-api-secret
  targetName: mysql-secret
  refreshInterval: "1h"
  
  data:
    mysql:
      key: "mysql"
      properties:
        MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
        MYSQL_DATABASE: "MYSQL_DATABASE"
        DATABASE_URL: "DATABASE_URL"
  dataFrom:
    extract:
      key: "mysql"



# Database values.yaml
database:
  replicaCount: 1
  mysql:
    rootPasswordKey: MYSQL_ROOT_PASSWORD  # Key to fetch from the external secret
    databaseKey: MYSQL_DATABASE            # Key to fetch from the external secret
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    enabled: true
    type: ClusterIP
    port: 3306

# API value.yaml
api:
  replicaCount: 1

  image:
    repository: rajeshecb70/flask-api
    tag: "10.0.0"

  migrationImage:
    repository: rajeshecb70/flask-api
    tag: "10.0.0"

  containerPort: 5000

  service:
    port: 5000