name: CI Pipeline

on:
  push:
    branches:
      - milestone-04/pipeline
    paths:
      - 'milestone-04/**'
  pull_request:
    branches:
      - milestone-04/pipeline
    paths:
      - 'milestone-04/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Step 4: Check the contents of milestone-04
      - name: List files in milestone-04
        run: |
          ls -l milestone-04

      # Step 5: Check if Makefile exists
      - name: Check Makefile
        run: |
          if [ ! -f milestone-04/Makefile ]; then
            echo "Makefile not found in milestone-04 directory!"
            exit 1
          fi

      # Step 6: Build the Docker image
      - name: Build Docker image
        working-directory: milestone-04
        run: make docker-build  # Ensure your Makefile handles the build

      # Step 7: Start the Database
      - name: Start Database
        working-directory: milestone-04
        run: |
          docker-compose up -d db  # Ensure you have a 'db' service in your docker-compose.yml
          sleep 10  # Wait for the database to be ready

      # Step 7: Start the Database
      - name: Start 
        working-directory: milestone-04
        run: |
          docker-compose up -d flask-api  # Ensure you have a 'db' service in your docker-compose.yml
          sleep 10  # Wait for the appy to be ready

      # Step 8: Install dependencies and run tests
      - name: Install dependencies and run tests
        working-directory: milestone-04
        run: |
          make install-dependencies  # Ensure your Makefile can install dependencies
          make test-flask  # Run the tests

      # Step 9: Stop and remove containers
      - name: Stop and remove containers
        working-directory: milestone-04
        run: docker-compose down

      # Optional: Docker login and push steps can be uncommented if needed
      # - name: Docker login
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker push
      #   run: |
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-api:3.0.0
