name: CI Pipeline

on:
  push:
    branches:
      - milestone-04/pipeline
    paths:
      - 'milestone-04/**'
  pull_request:
    branches:
      - milestone-04/pipeline
    paths:
      - 'milestone-04/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Check if Makefile exists
      - name: Check Makefile
        run: |
          ls -l
          if [ ! -f Makefile ]; then
            echo "Makefile not found!"
            exit 1
          fi

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: make docker-build  # Ensure your Makefile handles the build

      # Step 5: Start the Database
      - name: Start Database
        run: |
          docker-compose up -d db  # Ensure you have a 'db' service in your docker-compose.yml
          sleep 10  # Wait for the database to be ready

      # Step 6: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          make install-dependencies  # Ensure your Makefile can install dependencies
          make test-flask  # Run the tests

      # Step 7: Stop and remove containers
      - name: Stop and remove containers
        run: docker-compose down

      # Optional: Docker login and push steps can be uncommented if needed
      # - name: Docker login
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker push
      #   run: |
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-api:3.0.0
