name: Milestone Branch CI

# Define the event that triggers the workflow
on:
  push:
    branches:
      - milestone-04/pipeline  # Trigger only on the milestone branch

# Define the jobs that will be executed
jobs:
  hello-world-job:
    # Use a GitHub-hosted runner (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run a script that prints "Hello World"
      - name: Say Hello World
        run: echo "Hello World"
